// Thapar campus locations mapped from the newer Loc8TIET dataset:
// https://loc8tiet.netlify.app/
// The older Scribble Maps link is intentionally not used as a source of truth.

export const CAMPUS_CENTER: [number, number] = [76.3623, 30.3571]
export const CAMPUS_ZOOM = 17

export interface BuildingPin {
  id: string
  name: string
  short_name: string
  category: string
  coordinates: [number, number]
  description?: string
}

const categoryColors: Record<string, string> = {
  Academic: '#185FA5',
  Residential: '#6D28D9',
  Dining: '#D97706',
  Commercial: '#B45309',
  'Event Space': '#BE185D',
  Administration: '#475569',
  Innovation: '#0F766E',
  Research: '#2563EB',
  Health: '#DC2626',
  Access: '#16A34A',
  Bank: '#334155',
}

export function getCampusCategoryColor(category: string) {
  return categoryColors[category] ?? '#185FA5'
}

export const CAMPUS_CATEGORIES = Object.keys(categoryColors)

export const CAMPUS_BUILDINGS: BuildingPin[] = [
  {
    id: 'agira-hall',
    name: 'Agira Hall',
    short_name: 'Agira',
    category: 'Residential',
    coordinates: [76.36004, 30.35580],
    description: "Boys' hostel, formerly Hostel-A.",
  },
  {
    id: 'ambaram-hall',
    name: 'Ambaram Hall',
    short_name: 'Ambaram',
    category: 'Residential',
    coordinates: [76.36114, 30.35519],
    description: 'Hostel-K, renamed Ambaram Hall.',
  },
  {
    id: 'amritam-hall',
    name: 'Amritam Hall',
    short_name: 'Amritam',
    category: 'Residential',
    coordinates: [76.35955, 30.35635],
    description: 'Male residential block, formerly Hostel-B.',
  },
  {
    id: 'ananta-hall',
    name: 'Ananta Hall',
    short_name: 'Ananta',
    category: 'Residential',
    coordinates: [76.36078, 30.35447],
    description: 'Hostel-N with upgraded student facilities.',
  },
  {
    id: 'anantam-hall',
    name: 'Anantam Hall',
    short_name: 'Anantam',
    category: 'Residential',
    coordinates: [76.36462, 30.35913],
    description: 'Hostel-M with spacious living areas.',
  },
  {
    id: 'auditorium',
    name: 'Auditorium',
    short_name: 'Auditorium',
    category: 'Event Space',
    coordinates: [76.35946, 30.35440],
    description: 'Major cultural events, seminars, guest lectures, and convocations.',
  },
  {
    id: 'c-block',
    name: 'C-Block',
    short_name: 'C-Block',
    category: 'Academic',
    coordinates: [76.36529, 30.35705],
    description: 'EIED department classrooms, labs, and faculty rooms.',
  },
  {
    id: 'c-hall',
    name: 'C-hall',
    short_name: 'C-hall',
    category: 'Event Space',
    coordinates: [76.36529, 30.35445],
    description: 'Cultural and technical events, seminars, and guest lectures.',
  },
  {
    id: 'cos-complex',
    name: 'Cos Complex',
    short_name: 'Cos Complex',
    category: 'Commercial',
    coordinates: [76.36111, 30.35654],
    description: 'Shopping and convenience hub with stationery, salons, ATMs, and food stalls.',
  },
  {
    id: 'csed',
    name: 'CSED - Computer Science and Engineering Department',
    short_name: 'CSED',
    category: 'Research',
    coordinates: [76.36040, 30.35677],
    description: 'Computer Science and Engineering department.',
  },
  {
    id: 'dhriti-hall',
    name: 'Dhriti Hall (PG Hostel)',
    short_name: 'Dhriti',
    category: 'Residential',
    coordinates: [76.36394, 30.35756],
    description: "Girls' postgraduate hostel.",
  },
  {
    id: 'directorate',
    name: 'Directorate',
    short_name: 'Directorate',
    category: 'Administration',
    coordinates: [76.36490, 30.35605],
    description: 'Administrative headquarters of Thapar Institute.',
  },
  {
    id: 'e-block',
    name: 'E-Block',
    short_name: 'E-Block',
    category: 'Academic',
    coordinates: [76.36461, 30.35895],
    description: 'Academic block with lecture halls, faculty offices, and labs.',
  },
  {
    id: 'elc',
    name: 'ELC - Experiential Learning Centre',
    short_name: 'ELC',
    category: 'Innovation',
    coordinates: [76.36463, 30.35474],
    description: 'Hands-on learning, prototyping, and interdisciplinary projects.',
  },
  {
    id: 'f-block',
    name: 'F-Block',
    short_name: 'F-Block',
    category: 'Academic',
    coordinates: [76.36272, 30.35916],
    description: 'Academic block for classes and faculty meetings.',
  },
  {
    id: 'g-block',
    name: 'G-Block',
    short_name: 'G-Block',
    category: 'Academic',
    coordinates: [76.36355, 30.35799],
    description: 'Chemistry, Mathematics, Physics, and TICC.',
  },
  {
    id: 'g-block-canteen',
    name: 'G-Block Canteen',
    short_name: 'G Canteen',
    category: 'Commercial',
    coordinates: [76.35922, 30.35469],
    description: 'Home-cooked meals, beverages, and snacks.',
  },
  {
    id: 'h-block',
    name: 'H-Block',
    short_name: 'H-Block',
    category: 'Academic',
    coordinates: [76.35832, 30.35792],
    description: 'Research, classrooms, and postgraduate studies.',
  },
  {
    id: 'health-centre',
    name: 'Health Centre',
    short_name: 'Health',
    category: 'Health',
    coordinates: [76.35820, 30.35490],
    description: 'Health consultations, emergency care, and first aid.',
  },
  {
    id: 'hostel-frf',
    name: 'Hostel FRF',
    short_name: 'FRF',
    category: 'Residential',
    coordinates: [76.35929, 30.35782],
    description: 'UG and PG girls hostel.',
  },
  {
    id: 'hostel-frg',
    name: 'Hostel FRG',
    short_name: 'FRG',
    category: 'Residential',
    coordinates: [76.36376, 30.35937],
    description: 'UG and PG girls hostel.',
  },
  {
    id: 'ira-hall',
    name: 'Ira Hall',
    short_name: 'Ira',
    category: 'Residential',
    coordinates: [76.36205, 30.35504],
    description: "Girls' hostel, formerly Hostel-I.",
  },
  {
    id: 'kravings',
    name: 'KRAVINGS',
    short_name: 'KRAVINGS',
    category: 'Dining',
    coordinates: [76.36266, 30.35428],
    description: 'Campus food court with multiple outlets.',
  },
  {
    id: 'library',
    name: 'Library',
    short_name: 'Library',
    category: 'Academic',
    coordinates: [76.35805, 30.35536],
    description: 'Central knowledge hub and reading zones.',
  },
  {
    id: 'lt-lp',
    name: 'LT & LP',
    short_name: 'LT & LP',
    category: 'Academic',
    coordinates: [76.36353, 30.35637],
    description: 'Student lecture halls.',
  },
  {
    id: 'main-gate',
    name: 'Main Gate',
    short_name: 'Main Gate',
    category: 'Access',
    coordinates: [76.36258, 30.35439],
    description: 'Primary campus entrance.',
  },
  {
    id: 'mechanical-department',
    name: 'MECHANICAL Department',
    short_name: 'Mechanical',
    category: 'Academic',
    coordinates: [76.35918, 30.35586],
    description: 'Mechanical engineering department.',
  },
  {
    id: 'neeram-hall',
    name: 'Neeram Hall',
    short_name: 'Neeram',
    category: 'Residential',
    coordinates: [76.36546, 30.35575],
    description: 'Hostel-D for boys.',
  },
  {
    id: 'open-air-theatre',
    name: 'Open Air Theatre (OAT)',
    short_name: 'OAT',
    category: 'Event Space',
    coordinates: [76.36320, 30.35734],
    description: 'Outdoor amphitheater for fests, screenings, and live music.',
  },
  {
    id: 'prithvi-hall',
    name: 'Prithvi Hall',
    short_name: 'Prithvi',
    category: 'Residential',
    coordinates: [76.35936, 30.35892],
    description: 'Hostel-C for boys.',
  },
  {
    id: 'sbi-bank',
    name: 'SBI Bank',
    short_name: 'SBI',
    category: 'Bank',
    coordinates: [76.36291, 30.35687],
    description: 'SBI bank branch.',
  },
  {
    id: 'street',
    name: 'Street',
    short_name: 'Street',
    category: 'Dining',
    coordinates: [76.36220, 30.35684],
    description: 'Sodexo canteen and food court.',
  },
  {
    id: 'tan-building',
    name: 'TAN Building',
    short_name: 'TAN',
    category: 'Innovation',
    coordinates: [76.36105, 30.35411],
    description: 'Entrepreneurship and technology incubation facility.',
  },
  {
    id: 'tejas-hall',
    name: 'Tejas Hall',
    short_name: 'Tejas',
    category: 'Residential',
    coordinates: [76.36034, 30.35598],
    description: 'Modern male student hostel.',
  },
  {
    id: 'tslas',
    name: 'TSLAS - Thapar School of Liberal Arts and Sciences',
    short_name: 'TSLAS',
    category: 'Academic',
    coordinates: [76.36217, 30.35747],
    description: 'Thapar School of Liberal Arts and Sciences.',
  },
  {
    id: 'vahni-hall',
    name: 'Vahni Hall',
    short_name: 'Vahni',
    category: 'Residential',
    coordinates: [76.35909, 30.35866],
    description: "Girls' hostel, formerly Hostel-Q.",
  },
  {
    id: 'vasudha-hall-e',
    name: 'Vasudha Hall (E)',
    short_name: 'Vasudha E',
    category: 'Residential',
    coordinates: [76.36395, 30.35615],
    description: "Girls' hostel with residential facilities.",
  },
  {
    id: 'vasudha-hall-g',
    name: 'Vasudha Hall (G)',
    short_name: 'Vasudha G',
    category: 'Residential',
    coordinates: [76.36185, 30.35970],
    description: 'Former Hostel-G for girls.',
  },
  {
    id: 'venture-lab',
    name: 'Venture Lab',
    short_name: 'Venture Lab',
    category: 'Academic',
    coordinates: [76.36000, 30.35461],
    description: 'Innovation and entrepreneurial development space.',
  },
  {
    id: 'viyat-hall',
    name: 'Viyat Hall',
    short_name: 'Viyat',
    category: 'Residential',
    coordinates: [76.36007, 30.35824],
    description: 'Hostel-L for male students.',
  },
  {
    id: 'vyan-hall',
    name: 'Vyan Hall',
    short_name: 'Vyan',
    category: 'Residential',
    coordinates: [76.36081, 30.35585],
    description: 'Hostel-H for male students.',
  },
  {
    id: 'vyom-hall',
    name: 'Vyom Hall',
    short_name: 'Vyom',
    category: 'Residential',
    coordinates: [76.35838, 30.35755],
    description: 'Hostel-O for boys.',
  },
]
